services:

  demo:
    build:
      context: .
      target: demo
    ports:
      - '8080:80'
    environment:
      APP_ENV: 'dev'
    volumes: &volumes
      - ./:/app

  # Use the container below for development tools (composer, ...)
  dev:
    image: registry.gitlab.com/arnapou/docker/php:8.4-dev
    volumes: *volumes
