services:

  app:
    build: .
    user: 1000:1000
    volumes: &volumes
      - ./:/app

  # Use the container below for development tools (composer, ...)
  dev:
    image: registry.gitlab.com/arnapou/docker/php:8.3-dev
    user: 1000:1000
    volumes: *volumes
